FROM python:3.13-alpine

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY ./api /api

# Install the application dependencies.
WORKDIR /api
RUN uv sync --frozen --no-cache

# Run the worker.
CMD ["/api/.venv/bin/python", "worker.py"] 